/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#0047AB',
        'primary-container': '#0047AB',
        'on-primary': '#FFFFFF',
        'primary-fixed': '#0047AB',
        secondary: '#656C77',
        'secondary-container': '#DEE0EB',
        'on-secondary': '#FFFFFF',
        tertiary: '#7B4F5C',
        'tertiary-container': '#FFD9E2',
        'on-tertiary': '#FFFFFF',
        error: '#B3261E',
        'error-container': '#F9DEDC',
        'on-error': '#FFFFFF',
        background: '#FFFBFE',
        'on-background': '#1C1B1F',
        surface: '#FFFBFE',
        'surface-variant': '#E7E0EC',
        'on-surface-variant': '#49454F',
        outline: '#79747E',
        'outline-variant': '#CAC4D0',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F7F2FA',
        'surface-container': '#F3EEF6',
        'surface-container-high': '#ECE6F0',
        'surface-container-highest': '#E6E1E5',
        'on-error-container': '#93000A',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        manrope: ['Manrope', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['3.5rem', { lineHeight: '4rem', letterSpacing: '0' }],
        'display-md': ['3rem', { lineHeight: '3.5rem', letterSpacing: '0' }],
        'display-sm': ['2.75rem', { lineHeight: '3rem', letterSpacing: '0' }],
        'headline-lg': ['2rem', { lineHeight: '2.5rem', letterSpacing: '0' }],
        'headline-md': ['1.75rem', { lineHeight: '2.25rem', letterSpacing: '0' }],
        'headline-sm': ['1.5rem', { lineHeight: '2rem', letterSpacing: '0' }],
        'title-lg': ['1.375rem', { lineHeight: '1.75rem', letterSpacing: '0.125rem' }],
        'title-md': ['1rem', { lineHeight: '1.5rem', letterSpacing: '0.15rem' }],
        'title-sm': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0.1rem' }],
        'body-lg': ['1rem', { lineHeight: '1.5rem', letterSpacing: '0.5rem' }],
        'body-md': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0.4rem' }],
        'body-sm': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.4rem' }],
        'label-lg': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.5rem' }],
        'label-md': ['0.6875rem', { lineHeight: '1rem', letterSpacing: '0.5rem' }],
        'label-sm': ['0.625rem', { lineHeight: '0.75rem', letterSpacing: '0.3rem' }],
      },
      boxShadow: {
        'elevation-0': 'none',
        'elevation-1': '0px 1px 3px 1px rgba(0, 0, 0, 0.15), 0px 1px 2px 0px rgba(0, 0, 0, 0.3)',
        'elevation-2': '0px 2px 6px 2px rgba(0, 0, 0, 0.15), 0px 1px 2px 0px rgba(0, 0, 0, 0.3)',
        'elevation-3': '0px 4px 8px 3px rgba(0, 0, 0, 0.15), 0px 1px 3px 0px rgba(0, 0, 0, 0.3)',
        'elevation-4': '0px 5px 10px 4px rgba(0, 0, 0, 0.15), 0px 1px 3px 0px rgba(0, 0, 0, 0.3)',
        'elevation-5': '0px 7px 14px 4px rgba(0, 0, 0, 0.15), 0px 1px 3px 0px rgba(0, 0, 0, 0.3)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
